### ISSUE TITLE
docker installation

### ISSUE THREAD

**Issue by hodanli** [dimitrov-adrian/directus-extension-searchsync#29]
how can i install this extension to directus docker container?

**Comment by Lukas-Sachse** [comment]
Hi @hodanli, these are my steps for working with docker:

# [Demo with a step-by-step-tutorial](https://github.com/Lukas-Sachse/directus-extension-searchsync-docker-demo)

## What we are doing
Instead of using the official directus-image directly, we will build our own custom image  that's extending the official image.


## Required
Own repository with Dockerfile, docker-compose.yml and a valid searchsync-config-file.
[Take a look at my demo](https://github.com/Lukas-Sachse/directus-extension-searchsync-docker-demo)
#### Example: searchsync.config.cjs
```js
module.exports = {
  server: {
    type: 'meilisearch',
    host: 'http://host.docker.internal:7700',
    key: '<your-api-key>',
  },
  reindexOnStart: true,
  collections: {
    test_collection: {
      fields: ['title', 'description'],
    },
  },
}

```

#### Build custom image with Dockerfile:
```YAML

FROM directus/directus:9.23.1

# Install git 
# We need this part becaus "npm install" will fail without the git package.
# Installing apk packages needs permissions, so we need to switch to root user.
USER root  
RUN apk add git --no-cache 

# SearchSync extension
# First we copy the config file, then we install the extension.
COPY searchsync.config.cjs ./ 
RUN npm install dimitrov-adrian/directus-extension-searchsync

# Start command for our image
CMD npx directus bootstrap && \
  npx directus database migrate:latest && \
  npx directus start 
```

#### Snippet from docker-compose.yml
```yaml

[...]

services:
 [...]
  custom-directus:
    container_name: custom-directus
    # build the image from the Dockerfile in the current directory
    # ---
    build: 
      context: ./
      dockerfile: Dockerfile
     # ---
 [...]
```
